export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <section className="flex flex-col items-center justify-center bg-white h-screen">
      {children}
      </section>
  )
}
