import { AuthProvider, QueryProvider } from '@/provider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <QueryProvider>
          <body>
            {children}
          </body>
        </QueryProvider>
      </AuthProvider>
    </html>
  )
}
